config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #~ get '/', to: 'contacts#index', as: :home
  root to: 'users#new'
  scope 'api' do


  #contacts
  get '/contact/new', to: 'contacts#new', as: :new_contact_form
  post '/contact', to: 'contacts#create', as: :create_new_contact
  get '/contact', to: 'contacts#index', as: :show_all_user_contacts
  get '/contact/:id', to: 'contacts#show', as: :show_single_contact
  get '/contact/show_starred/:user', to: 'contacts#starred', as: :show_starred_contacts
  get '/contact/:id/edit', to: 'contacts#edit', as: :edit_contact_form
  patch '/contact/:id', to: 'contacts#update', as: :update_single_contact
  delete '/contact/:id', to: 'contacts#destroy', as: :delete_single_contact
  patch '/contact/:id/star', to: 'contacts#star', as: :star_single_contact


  #users
  get '/user/signup', to: 'users#new', as: :signup_form
  post '/user/signin', to: 'users#authenticate', as: :authenticate
  post '/user/signup', to: 'users#create', as: :do_signup
  get '/user/signin', to: 'users#signin', as: :login
  get '/user/logout', to: 'users#logout', as: :logout
  get '/users', to: 'users#index', as: :all_users
  get '/user/me', to: 'users#me', as: :my_profile
  get '/user/:id', to: 'users#show', as: :show_single_user
  patch '/user/:id', to: 'users#update', as: :update_single_user
  delete '/user/:id', to: 'users#destroy', as: :delete_single_user

  end
end

app/models/user.rb
class User < ApplicationRecord
  #~ before_create :encrypt_password
  #~ attr_accessor :username, :email, :password, :confirm_password


  # validation
  #~ validates :username, uniqueness: true
  #~ validates :email, uniqueness: true

  #~ validates_length_of     :email, :within => 3..150
  #~ validates_uniqueness_of :email, :case_sensitive => false
  #~ validates_presence_of   :username
  #~ validates_length_of     :password, :within => 4..40
  #~ validates_confirmation_of :password, :if => :password?

  # encrypts given password using salt
  #~ def self.encrypt(pass, salt)
    #~ Digest::SHA1.hexdigest("--#{salt}--#{pass}--" )
  #~ end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/signin
  def signin
  end

  # GET /users/1/edit
  def edit
    @contact = Contact.find_by(:id)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new()
    @user.username = params[:username]
    @user.encrypted_password = params[:password]
    @user.email = params[:email]
    confirm_password = params[:confirm_password]

    if params[:password].to_s == params[:confirm_password].to_s
      @user.salt = Digest::SHA1.hexdigest("--#{params[:username]}--" )
      @user.encrypted_password = Digest::SHA1.hexdigest("--#{@user.salt}--#{params[:password]}--" )
      respond_to do |format|
        if @user.save
          format.html { redirect_to '/api/user/signin', notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to all_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_credentials

  end

  # authenticate by email/password
  def authenticate()
    salt = Digest::SHA1.hexdigest("--#{params[:username]}--" )
    tested_pass = Digest::SHA1.hexdigest("--#{salt}--#{params[:password]}--" )
    @user = User.find_by(:username => params[:username])
    if session[:user_id]
      redirect_to :controller => "users" , :action => "show" , :id => session[:user_id] and return
    end

    if @user && @user.encrypted_password == tested_pass
      session[:user_id] = @user.id
      session[:username] = @user.username
      flash[:notice] = "You are welcome back #{@user.username}!!"
      redirect_to show_all_user_contacts_path and return
    else
      flash[:notice] = "No user was found with this email/password"
      render :action => 'signin'
    end
  end

  # does the given password match the stored encrypted password
  def authenticated?
    saved_user = User.find_by(:username => session[:post_user])
    saved_pass = saved_user.encrypted_password
    post_pass = encrypt_password_string(session[:post_pass])
  end

  def encrypt_password_string(password)
    salt = Digest::SHA1.hexdigest("--#{params[:email]}--" )
    return  Digest::SHA1.hexdigest("--#{salt}--#{password}--" )
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path , :notice => 'You have been logged out!'
  end

  def me
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_tag({controller: "users", action: "new"}, method: "post") do |form|%>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Username:</br> <%= text_field_tag(:username,"", class: "form-control") %></p>
  <p>Password:</br> <%= password_field_tag(:password,"", class: "form-control") %></p>
  <p>Confirm password:</br> <%= password_field_tag(:confirm_password,"", class: "form-control") %></p>
  <p>Email:</br> <%= email_field_tag(:email,"", class: "form-control") %></p>
  <div class="actions">
    <%= submit_tag("Sign up",class: "btn btn-primary my-2") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<% if session[:user_id] %>
<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.username}", show_single_user_path(user) %></td>
        <td><%= link_to 'Edit', update_single_user_path(user) %></td>
        <td><%= link_to 'Destroy', delete_single_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<% if session[:user_id] == nil %>

  <%= link_to ' Login', signin_form_path %>
<% else %>

  <%= link_to ' | Logout', logout_path %>
<% end %>

app/views/users/me.html.erb
<% if session[:user_id] %>
  <p><b>Username: </b><%= @user.username %></p>
  <p><b>Email: </b><%= @user.email %></p>

  <br>
  <p><%= link_to 'Logout', logout_path %>
  </p>


<% end %>

app/views/users/new.html.erb
<h1 class="bg-light p-4">SignUp - Create new Acount</h1>
<div class="card p-3">
<%= render 'form', user: @user %>
</div>
<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', update_single_user_path(@user) %> |
<%= link_to 'Back', all_users_path %>

app/views/users/signin.html.erb
<div class= "Signin_Form ">
  <h1 class="bg-light p-3">Log in</h1>
  <% if notice %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>

  <fieldset class="m-4 p-3 border border-rounded">
    <legend>Enter username/password</legend>
    <% @page_title = "UserAuth | Login" -%>

      <%= form_tag(:action => 'authenticate') do %>
        <p>Username:</br> <%= text_field_tag(:username, "", {class: "form-control"}) %></p>
        <p>Password:</br> <%= password_field_tag( :password, "", {class: "form-control"}) %></p>
        <%= submit_tag("Log In", class: "btn btn-primary") %>
         <%= link_to ' | Signup', signup_form_path %>
      <% end %>
  </fieldset>
</div>