config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #~ get '/', to: 'contacts#index', as: :home
  root to: 'users#new'
  scope 'api' do


  #contacts
  get '/contact/new', to: 'contacts#new', as: :new_contact_form
  post '/contact', to: 'contacts#create', as: :create_new_contact
  get '/contact', to: 'contacts#index', as: :show_all_user_contacts
  get '/contact/:id', to: 'contacts#show', as: :show_single_contact
  get '/contact/show_starred/:user', to: 'contacts#starred', as: :show_starred_contacts
  get '/contact/:id/edit', to: 'contacts#edit', as: :edit_contact_form
  patch '/contact/:id', to: 'contacts#update', as: :update_single_contact
  delete '/contact/:id', to: 'contacts#destroy', as: :delete_single_contact
  patch '/contact/:id/star', to: 'contacts#star', as: :star_single_contact


  #users
  get '/user/signup', to: 'users#new', as: :signup_form
  post '/user/signin', to: 'users#authenticate', as: :authenticate
  post '/user/signup', to: 'users#create', as: :do_signup
  get '/user/signin', to: 'users#signin', as: :login
  get '/user/logout', to: 'users#logout', as: :logout
  get '/users', to: 'users#index', as: :all_users
  get '/user/me', to: 'users#me', as: :my_profile
  get '/user/:id', to: 'users#show', as: :show_single_user
  patch '/user/:id', to: 'users#update', as: :update_single_user
  delete '/user/:id', to: 'users#destroy', as: :delete_single_user

  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_starring_user, only: [:starred]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.name = params[:name]
    @contact.address = params[:address]
    @contact.user_id = session[:user_id]
    @contact.starred = params[:starred]
    respond_to do |format|
      if @contact.save
        format.html { redirect_to '/api/contact', notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      @contact.name = params[:name]
      @contact.user_id = session[:user_id]
      @contact.address = params[:address]
      @contact.starred = params[:starred]
      if @contact.save()
        format.html { redirect_to show_all_user_contacts_url, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to show_all_user_contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def starred
    if session[:user_id]
      @contacts = Contact.where(:user_id => session[:user_id]).where(:starred => true)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_starring_user
      @contacts = Contact.find_by(:user_id => session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.fetch(:contact, {})
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= form_tag({controller: "contacts", action: "update"}, method: "patch") do %>
  <% if @contact.errors.any? %>
    <div id="alert alert-danger">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= label_tag(:name, "Contact name:") %><br>
  <%= text_field_tag(:name, "#{@contact.name}", class: "form-control")  %></p>
  <%= hidden_field_tag(:user_id, "#{session[:user_id]}") %>
  <p><%= label_tag(:address, "Address:") %><br>
  <%= text_area_tag(:address, "#{@contact.address}", class: "form-control") %></p>
  <p><%= label_tag(:starred, "Starred?") %>
  <% if @contact.starred?  %>
    <%= check_box_tag(:starred, '1', true) %>
  <% else %>
    <%= check_box_tag(:starred) %>
  <% end %>
  </p>

  <div class="actions">
    <%= submit_tag "Save Contact", class: "btn btn-primary my-2" %>
  </div>
<% end %>


<%= link_to 'Show', show_single_contact_path %> |
<%= link_to 'Back', show_all_user_contacts_path %>

app/views/contacts/index.html.erb
<% if notice %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<h3>My Contacts <em><small><%= link_to 'show only starred contacts', show_starred_contacts_path(session[:user_id]) %></small></em></h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to "#{contact.name}", show_single_contact_path(contact) %>
          <% if contact.starred %>
            <span class="text-warning">
            <i class="fas fa-star"></i>
            <em><small>starred</small></em>
            </span>
          <% end %>
        </td>
        <td><%= link_to (raw("<span class=''><i class='far fa-trash-alt'></i> Edit </span>")), edit_contact_form_path(contact) %></td>
        <td><%= link_to (raw("<span class='text-danger'><i class='far fa-trash-alt'></i> Delete</span>")), delete_single_contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to (raw("<span class='btn btn-success'>New Contact </span>")), new_contact_form_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_tag({controller: "contacts", action: "create"}, method: "post") do %>
  <% if @contact.errors.any? %>
    <div id="alert alert-danger">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= label_tag(:name, "Contact name:") %><br>
  <%= text_field_tag(:name, "#{@contact.name}", class: "form-control")  %></p>
  <%= hidden_field_tag(:user_id, "#{session[:user_id]}") %>
  <p><%= label_tag(:address, "Address:") %><br>
  <%= text_area_tag(:address, "#{@contact.address}", class: "form-control") %></p>
  <p><%= label_tag(:starred, "Starred?") %>
  <%= check_box_tag(:starred) %></p>

  <div class="actions">
    <%= submit_tag "Save Contact", class: "btn btn-primary my-2" %>
    <%= submit_tag "Back", class: "btn btn-default my-2" %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @contact.name %></h1>
<p><%= @contact.address %></p>
<%=
  if @contact.starred do
    print starred
    end
  end
%>
<%= link_to 'Edit', edit_contact_form_path(@contact) %> |
<%= link_to 'Back', show_all_user_contacts_path %>

app/views/contacts/starred.html.erb
<p id="notice"><%= notice %></p>

<h3>My Starred Contacts</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to "#{contact.name}", show_single_contact_path(contact) %>
          <% if contact.starred %>
            <span class="text-warning">
            <i class="fas fa-star"></i>
            <em><small>starred</small></em>
            </span>
          <% end %>
        </td>
        <td><%= link_to (raw("<span class=''><i class='far fa-trash-alt'></i> Edit </span>")), edit_contact_form_path(contact) %></td>
        <td><%= link_to (raw("<span class='text-danger'><i class='far fa-trash-alt'></i> Delete</span>")), delete_single_contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to (raw("<span class='btn btn-success'>New Contact </span>")), new_contact_form_path %>