config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #~ get '/', to: 'contacts#index', as: :home
  root to: 'users#new'
  scope 'api' do


  #contacts
  get '/contact/new', to: 'contacts#new', as: :new_contact_form
  post '/contact', to: 'contacts#create', as: :create_new_contact
  get '/contact', to: 'contacts#index', as: :show_all_user_contacts
  get '/contact/:id', to: 'contacts#show', as: :show_single_contact
  get '/contact/show_starred/:user', to: 'contacts#starred', as: :show_starred_contacts
  get '/contact/:id/edit', to: 'contacts#edit', as: :edit_contact_form
  patch '/contact/:id', to: 'contacts#update', as: :update_single_contact
  delete '/contact/:id', to: 'contacts#destroy', as: :delete_single_contact
  patch '/contact/:id/star', to: 'contacts#star', as: :star_single_contact


  #users
  get '/user/signup', to: 'users#new', as: :signup_form
  post '/user/signin', to: 'users#authenticate', as: :authenticate
  post '/user/signup', to: 'users#create', as: :do_signup
  get '/user/signin', to: 'users#signin', as: :login
  get '/user/logout', to: 'users#logout', as: :logout
  get '/users', to: 'users#index', as: :all_users
  get '/user/me', to: 'users#me', as: :my_profile
  get '/user/:id', to: 'users#show', as: :show_single_user
  patch '/user/:id', to: 'users#update', as: :update_single_user
  delete '/user/:id', to: 'users#destroy', as: :delete_single_user

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if session[:user_id] %>
      <h1 class="bg-secondary p-4 text-white">Fluid Angle Assessment Contact Api</h1>
      <h3 class="bg-light border mb-3 p-3">
        <i class="fas fa-user"></i><%= link_to ' My profile', my_profile_path %> |
        <i class="far fa-address-book"></i> <%= link_to 'Address book', show_all_user_contacts_path %>
      </h3>
    <% end %>
      <div class="container">
        <%= yield %>
      </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</html>